version: '2.1'
services:
  web:
    build: 
        context: .
        dockerfile: Web.dockerfile
    depends_on:
      - db
  job-server:
    build: 
        context: .
        dockerfile: JobServer.dockerfile
    depends_on:
      - db
  socket-message-bus:
    build: 
        context: .
        dockerfile: SocketMessageBus.dockerfile
    networks:
      default:
        ipv4_address: 172.18.209.3
        aliases:
          - socket-message-bus
  db:
    build:
        context: .
        dockerfile: Sql.dockerfile
    environment:
      sa_password: "JeRf5P7uw0"
      ACCEPT_EULA: "y"
    networks:
      default:
        ipv4_address: 172.18.209.1
        aliases:
          - db
    
networks:
  default:
    external:
      name: nat